sudo: false
language: nodejs
nodejs:
- "8"
- "9"

addons:
  code_climate:
    repo_token: 4571e140f40fc715f594cfe78ddacad87d10c114a0c921e5d00e1c6758a803e7

before_script:
  - npm install

script:
  - npm test

after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info